# Generated by Django 3.0.7 on 2020-06-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_helper', '0008_auto_20200604_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('blocks', models.ManyToManyField(to='academic_helper.StudyBlock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='School',
            new_name='Department',
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
